### Create User and Profile
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":"tegar",
    "email":"tegar@gmail.com",
    "password":"123456",
    "identity_type":"KTP", 
    "identity_number":"000111222555", 
    "address":"Bojonegoro"
}

### Get all User 
GET http://localhost:3000/api/v1/users?search=

### Get User by ID 
GET http://localhost:3000/api/v1/users/4





### Create Account
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "bank_name":"BCA",
    "bank_account_number":"155000555",
    "balance":120000,
    "user_id":5
}

### Get all Account
GET http://localhost:3000/api/v1/accounts

### Get Account by ID
GET http://localhost:3000/api/v1/accounts/3




### Create Transaction
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "amount":10000,
    "source_account_id":4,
    "source_destination_id":5
}

### Get all Transaction
GET http://localhost:3000/api/v1/transactions

### Get Transaction by ID
GET http://localhost:3000/api/v1/transactions/7